
package org.echo.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EchoServiceName", targetNamespace = "http://echo.org/echoserviceX", wsdlLocation = "http://localhost:8081/echo_service-1.0/echoService?wsdl")
public class EchoServiceName
    extends Service
{

    private final static URL ECHOSERVICENAME_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.echo.jaxws.EchoServiceName.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.echo.jaxws.EchoServiceName.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/echo_service-1.0/echoService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/echo_service-1.0/echoService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ECHOSERVICENAME_WSDL_LOCATION = url;
    }

    public EchoServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoServiceName() {
        super(ECHOSERVICENAME_WSDL_LOCATION, new QName("http://echo.org/echoserviceX", "EchoServiceName"));
    }

    /**
     * 
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServicePort")
    public EchoService getEchoServicePort() {
        return super.getPort(new QName("http://echo.org/echoserviceX", "EchoServicePort"), EchoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServicePort")
    public EchoService getEchoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://echo.org/echoserviceX", "EchoServicePort"), EchoService.class, features);
    }

}
